version: '3'

networks:
  internet:
    driver: bridge
  no-internet:
    internal: true
    driver: bridge


services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache:/etc/nginx/cache
    ports:
      - 80:80
      - 443:443
    networks:
      - internet
      - no-internet

  backend:
    image: simple-backend:dev
    container_name: backend
    ports:
      - 8080:8080
    expose:
      - "8080"
    networks:
      - no-internet
